### ISSUE TITLE
Suggestion: stick closer to existing Ubuntu standards?

### ISSUE THREAD

**Issue by lproven** [mattkae/miracle-wm#102]
Some numbered examples.

1. The standard Ubuntu keystroke to open a terminal window is Ctrl+Alt+T. This is honoured in most remixes, in Mint and some related projects such as Zorin OS.

I suggest sticking to the defaults where possible.

2. Ubuntu is GNOME-based by default.

So the default terminal emulator is `gnome-terminal`, not `konsole`. I think only Kubuntu uses that.

And other remixes use GNOME tools, such as Ubuntu Cinnamon, and up to a point Ubuntu Unity, Ubuntu Budgie, and others.

3. Fonts. When I install `waybar` most of the indicators show "tofu" characters: a small box containing hex digits. I don't know what they are supposed to look like. If a particular font is needed for these icons, then list it so we know what to install.  

4. Dependencies. It was not clear to me that as well as the snap I needed to install `swaybg`, `waybar`, `wofi`, and change the terminal emulator command. And, as in point 3, an unknown font. Specify the dependencies up front, or better still, include them in the snap?

**Comment by Conan-Kudo** [comment]
Miracle is not really tied to Ubuntu. It's a personal project of @mattkae's that's built on Mir.

**Comment by lidgnulinux** [comment]
> Miracle is not really tied to Ubuntu. It's a personal project of @mattkae's that's built on Mir.

So this issue is kind of irrelevant, right ?

**Comment by mattkae** [comment]
> Some numbered examples.
> 
>     1. The standard Ubuntu keystroke to open a terminal window is Ctrl+Alt+T. This is honoured in most remixes, in Mint and some related projects such as Zorin OS.
> 

I am more closely abiding by I3's rules here, since this compositor is meant to be i3-adjacent. A cute thing to do here would be to provide a "default Ubuntu-like tiling" config file for people to install if they like, but it is probably outside of the scope of this repo.

> I suggest sticking to the defaults where possible.
> 
>     2. Ubuntu is GNOME-based by default.
> 
> 
> So the default terminal emulator is `gnome-terminal`, not `konsole`. I think only Kubuntu uses that.

The default terminal is found by trying to resolve it in _some reasonable way_ on the end user's system. Again, this could be provided in the "default Ubuntu-like" config.

> 
> And other remixes use GNOME tools, such as Ubuntu Cinnamon, and up to a point Ubuntu Unity, Ubuntu Budgie, and others.
> 
>     3. Fonts. When I install `waybar` most of the indicators show "tofu" characters: a small box containing hex digits. I don't know what they are supposed to look like. If a particular font is needed for these icons, then list it so we know what to install.

Yeah `waybar` expects `font-awesome` to be installed out of the box (I never understood why it's not a dependency on that project though :laughing:)

> 
>     4. Dependencies. It was not clear to me that as well as the snap I needed to install `swaybg`, `waybar`, `wofi`, and change the terminal emulator command. And, as in point 3, an unknown font. Specify the dependencies up front, or better still, include them in the snap?

Those components are all optional, as miracle-wm is just a window manager and not a desktop environment. Hence, you could start any shell component that you like there.

All of this being said, I do agree that it would be nice to have a better "introductory" experience into miracle-wm, as you are presented with a black screen at the moment. I think https://github.com/mattkae/miracle-wm/issues/118 this ticket better sums up what we're looking for, and would be worthwhile to compile as a solid "first time user experience" type of deal.

**Comment by mattkae** [comment]
> > Some numbered examples.
> > ```
> > 1. The standard Ubuntu keystroke to open a terminal window is Ctrl+Alt+T. This is honoured in most remixes, in Mint and some related projects such as Zorin OS.
> > ```
> 
> I am more closely abiding by I3's rules here, since this compositor is meant to be i3-adjacent. A cute thing to do here would be to provide a "default Ubuntu-like tiling" config file for people to install if they like, but it is probably outside of the scope of this repo.
> 
> > I suggest sticking to the defaults where possible.
> > ```
> > 2. Ubuntu is GNOME-based by default.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So the default terminal emulator is `gnome-terminal`, not `konsole`. I think only Kubuntu uses that.
> 
> The default terminal is found by trying to resolve it in _some reasonable way_ on the end user's system. Again, this could be provided in the "default Ubuntu-like" config.
> 
> > And other remixes use GNOME tools, such as Ubuntu Cinnamon, and up to a point Ubuntu Unity, Ubuntu Budgie, and others.
> > ```
> > 3. Fonts. When I install `waybar` most of the indicators show "tofu" characters: a small box containing hex digits. I don't know what they are supposed to look like. If a particular font is needed for these icons, then list it so we know what to install.
> > ```
> 
> Yeah `waybar` expects `font-awesome` to be installed out of the box (I never understood why it's not a dependency on that project though 😆)
> 
> > ```
> > 4. Dependencies. It was not clear to me that as well as the snap I needed to install `swaybg`, `waybar`, `wofi`, and change the terminal emulator command. And, as in point 3, an unknown font. Specify the dependencies up front, or better still, include them in the snap?
> > ```
> 
> Those components are all optional, as miracle-wm is just a window manager and not a desktop environment. Hence, you could start any shell component that you like there.
> 
> All of this being said, I do agree that it would be nice to have a better "introductory" experience into miracle-wm, as you are presented with a black screen at the moment. I think #118 this ticket better sums up what we're looking for, and would be worthwhile to compile as a solid "first time user experience" type of deal.

Thanks for inspiring that ticket, it will help a lot of people :smile:
