### ISSUE TITLE
Fedora package?

### ISSUE THREAD

**Issue by Conan-Kudo** [mattkae/miracle-wm#28]
Mir has been packaged in Fedora for many years now. It'd be great to see MiracleWM packaged in Fedora by someone interested in this type of environment, and perhaps produce a Fedora spin. 😉

**Comment by mattkae** [comment]
First of all, congrats on being the first non-mattkae issue maker :wink: 

Second, yes definitely! I'll look into this soon. It shouldn't be very difficult to build miracle and package it across multiple platforms and architectures

**Comment by Conan-Kudo** [comment]
Feel free to reach out to me if you need any help!

**Comment by mattkae** [comment]
Hi @Conan-Kudo , I am going to look into this tomorrow (or tonight). Any tips on where I could get started (specifically if it references cmake, that would be great :smile: ) I have zero knowledge of packaging for RPM, so a definitive guide would be much appreciated

**Comment by Conan-Kudo** [comment]
The [RPM Packaging Guide](https://rpm-packaging-guide.github.io/) and the [Fedora Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/) are good starting places. Specifically for CMake type stuff, we have [a page on using CMake in RPM package builds](https://docs.fedoraproject.org/en-US/packaging-guidelines/CMake/).

You may also find [the Fedora package for Mir](https://src.fedoraproject.org/rpms/mir) to be helpful as a concrete example.

**Comment by mattkae** [comment]
@Conan-Kudo Is there a reason why the mir package in Fedora isn't on 2.16.3 (latest) for Fedora 38 and Fedora 39?

**Comment by mattkae** [comment]
(P.S.: I almost have a Fedora build for you :wink: It is much simpler than I thought!)

**Comment by Conan-Kudo** [comment]
Nobody has ever asked for it. I could update F39 since the MirAL ABI didn't break, but probably not F38 with how close to EOL it is. It is up to date in F40.

**Comment by mattkae** [comment]
> Nobody has ever asked for it. I could update F39 since the MirAL ABI didn't break, but probably not F38 with how close to EOL it is. It is up to date in F40.

F39 would be good for me :) Although I might as well just use F40

**Comment by Conan-Kudo** [comment]
Given that the F40 Beta ISOs are available now and it'll be released at the end of next month, F40 is probably the better bet. 😉
