### ISSUE TITLE
Mousing over X apps makes the mouse move ~50% slower on my machine

### ISSUE THREAD

**Issue by mattkae** [mattkae/miracle-wm#43]

**Comment by spongythecake** [comment]
Yes. I noticed if Miracle defaults to X11 support as its backend, true to your title, then the window manager as a whole inherits a slower mouse.

**Comment by mattkae** [comment]
Hm that's a good callout @spongythecake. I noticed that this correlated with my switching icon themes in gnome. Can you give me some more details as to what you're environment is like? Are you running Nvidia?
